name: "CodeProject.AI Server"
slug: codeproject_ai
version: "2.6.14"
description: "Local CodeProject.AI server with persistent storage"
url: "https://github.com/jasiek-b/ha-addons"

arch:
  - aarch64

startup: services
boot: auto
init: false

ports:
  32168/tcp: 32168
